services:

  # -------
  # ExpressJs
  # -------
  # app:
  #   build:
  #     context: ./backend
  #     target: development
  #   container_name: files_manager
  #   command: npm run dev
  #   volumes:
  #     - ./backend:/usr/src/app
  #   env_file:
  #     - .env
  #   ports:
  #     - "${EXPRESS_PORT}:${EXPRESS_PORT}"
  #     - "${EXPRESS_DEBUG_PORT}:${EXPRESS_DEBUG_PORT}"
  #   depends_on:
  #     - mongodb
  #     - redis
  # -------
  # MongoDB
  # -------
  mongodb:
    image: mongo:noble
    restart: unless-stopped
    container_name: mongodb
    environment:
      # MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongo-data:/data/db
    ports:
      - ${MONGO_PORT}:27017 # remove in prod

  mongodb-express:
    image: mongo-express:latest
    container_name: mongodb-express
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH: "false"
      # ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      # ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      # ME_CONFIG_BASICAUTH_USERNAME: admin
      # ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
  # -------
  # Redis
  # --requirepass ${REDIS_PASSWORD}
  # -------
  redis:
    image: redis:8.4.0
    restart: unless-stopped
    container_name: redis
    command: >
      redis-server
      --appendonly yes
      --dir /data
    ports:
      - "${REDIS_PORT}:6379" # remove in prod
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  mongo-data:
