services:

  # -------
  # ExpressJs
  # -------
  express:
    build:
      context: ./backend
      target: development
    container_name: express-dev
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/app/src
          ignore:
            - node_modules/
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    ports:
      - "${EXPRESS_PORT}:${EXPRESS_PORT}"
      - "${EXPRESS_DEBUG_PORT}:${EXPRESS_DEBUG_PORT}"

  # -------
  # MongoDB
  # -------
  mongodb:
    image: mongo:noble
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongo-data:/data/db
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT} # remove in prod

  mongodb-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "${MONGODB_EXPRESS_PORT}:${MONGODB_EXPRESS_PORT}"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongodb:27017
      ME_CONFIG_BASICAUTH_ENABLED: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb

  # -------
  # Redis
  # -------
  redis:
    image: edis:8.6-rc1-trixie
    restart: unless-stopped
    container_name: redis
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes
      --dir /data
    ports:
      - "${REDIS_PORT}:6379" # remove in prod
    volumes:
      - redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  redis-data:
  mongo-data:
